### PR TITLE
pre-incrementing is almost 10% faster

### PR DESCRIPTION
**Pull request by hl**
:boom:

### CODE REVIEW

**Comment by jeroenvisser101** [comment]
Cool! You tested that with the benchmark?

**Comment by hl** [comment]
good one, will do that :dancer:

**Comment by jeroenvisser101** [comment]
And how about

```
for ($i = 200; $i >= 0; --$i)
```

**Comment by jeroenvisser101** [comment]
Just did some tests, seems like --$i is a bit slower:

```
$i = 100; $i--: 20.955601930618 ms
$i = 100; --$i: 22.522354125977 ms
$i <= 100; $i++: 20.810256004333 ms
$i <= 100; ++$i: 20.891695022583 ms
```

Tests being:
``` php
benchmark('$i = 100; $i--', function () {
    for ($i = 100; $i >= 0; $i--) {
        $var = '';
    }
});

benchmark('$i = 100; --$i', function () {
    for ($i = 100; $i >= 0; --$i) {
        $var = '';
    }
});

benchmark('$i <= 100; $i++', function () {
    for ($i = 0; $i <= 100; ++$i) {
        $var = '';
    }
});

benchmark('$i <= 100; ++$i', function () {
    for ($i = 0; $i <= 100; ++$i) {
        $var = '';
    }
});
```

**Comment by jeroenvisser101** [comment]
Just did some tests, seems to be a bit faster, however, counting down is even faster!

```
$i = 100; $i--: 20.55216383934 ms
$i = 100; --$i: 19.622904062271 ms
$i <= 100; $i++: 20.385925769806 ms
$i <= 100; ++$i: 19.941976070404 ms
```

Test code:

``` php
benchmark('$i = 100; $i--', function () {
    for ($i = 100; $i >= 0; $i--) {
        $var = '';
    }
});

benchmark('$i = 100; --$i', function () {
    for ($i = 100; $i >= 0; --$i) {
        $var = '';
    }
});

benchmark('$i <= 100; $i++', function () {
    for ($i = 0; $i <= 100; ++$i) {
        $var = '';
    }
});

benchmark('$i <= 100; ++$i', function () {
    for ($i = 0; $i <= 100; ++$i) {
        $var = '';
    }
});
```

**Pull request merged**
